# This is a basic workflow to help you get started with Actions

name: update-blocklists

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:


    
jobs:
  update-blocklists:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Update Blocklists
        shell: pwsh
        run: |

          $Domains = @()

          mkdir Temp
          cd Temp

          $Request = Invoke-WebRequest https://lolrmm.io/api/rmm_tools.json
          $Data = ConvertFrom-Json $Request
          foreach ($Item in $Data)
          {
              if ($Item.Artifacts.Network.Count -gt 0)
              {
                  foreach ($Domain in $Item.Artifacts.Network[0].Domains)
                  {

                      $Domains += $Domain

                  }
              } else 
              {
                  continue
              }
          }

          if (Test-Path ./scamjam-remoteaccess.txt -PathType Any)
          {
            Remove-Item ./scamjam-remoteaccess.txt -Force
          }

          foreach ($Domain in $Domains)
          {
              if ($Domain -eq "user_managed")
              {
                  continue
              } else
              {
                  Add-Content -Path ./scamjam-remoteaccess.txt -Value $Domain
              }
              
          }
      - uses: ryand56/r2-upload-action@latest # Can be any release
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: temp
          destination-dir: . # Can be anything as long as it is an actual path
          output-file-url: false # defaults to true
          keep-file-fresh: true # defaults to false
